include = ["*.toml"]

[formatting]
indent_string = "    "
reorder_keys = false

[[rule]]
include = ["Cargo.toml"]
keys = ["dependencies", "lints.rust", "lints.clippy"]

[rule.formatting]
reorder_keys = true
reorder_arrays = true

[[rule]]
include = ["clippy.toml"]

[rule.formatting]
reorder_arrays = true
